<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$quote = $objectManager->create('Magento\Checkout\Model\Cart')->getQuote();
$itemsCount = $quote->getItemsCount();

$Names=array();
foreach ($quote->getAllItems() as $item) {
    array_push($Names,$item->getName());
}
?>
<form id="save" action="/savecomment/index/save" method="POST" style="margin-top:-300px">
    <?php for ($i = 1; $i <= $itemsCount; $i++) : ?>
        <span>order comment for item <?php echo $Names[$i-1] ?></span>
        <br>
        <input type="text" name="<?php echo "comment" . $i ?>" id="<?php echo "comment" . $i ?>" placeholder="order comment for item <?php echo $Names[$i-1] ?> ...." style="width: 631px;height: 50px;">
        <br>
        <br>
    <?php endfor; ?>
    <span>Write entire order comment here....</span><br>
    <input type="text" name="comment" id="comment" placeholder="Write entire order comment here...." style="width: 631px;height: 84px;">
</form>
<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $(document).on('click', '.primary', function() {
            $('#save').submit();
        })
        setTimeout(function(){
           var link=window.location.href;
            hashlink = link.split('#');
           if(hashlink[hashlink.length-1]==='shipping'){
                var element = document.getElementById("save");
                element.style.display='none';
            }
        },1000);
    });
</script>